version: "3"
services:
  rust-base-debian:
    # ─────────────────────────────────────────────────────────────────
    # docker-compose -f build.docker-compose.yml build --build-arg "BUILDKIT_INLINE_CACHE=1" rust-base-debian
    # ─────────────────────────────────────────────────────────────────
    image: fjolsvin/rust-base-debian
    build:
      context: ./base
      dockerfile: debian.dockerfile
      args:
        - MDBOOK_VERSION=0.4.5
        - CARGO_ABOUT_VERSION=0.2.3
        - CARGO_DENY_VERSION=0.8.5
        - OPENSSL_VERSION=1.1.1i
        - ZLIB_VERSION=1.2.11
        - POSTGRESQL_VERSION=11.9
        - TOOLCHAIN=nightly
      cache_from:
        - fjolsvin/rust-base-debian:latest

  # vscode-rust-debian:
  #   # ─────────────────────────────────────────────────────────────────
  #   # docker-compose -f build.docker-compose.yml build rust-debian
  #   # ─────────────────────────────────────────────────────────────────
  #   image: fjolsvin/rust-debian
  #   build:
  #     context: ./vscode
  #     dockerfile: debian.Dockerfile
  #     args:
  #       - USER=code
  #       - UID=1000
  #   depends_on:
  #     - rust-base-debian
