version: "3"
services:
  operator:
    image: fjolsvin/vscode-python-alpine
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ../:/workspace:cached
    command:
      - /bin/sh
      - -cex
      - while sleep 1000; do :; done