version: "3"
services:
  base:
    # ─────────────────────────────────────────────────────────────────
    # docker-compose build base
    # ─────────────────────────────────────────────────────────────────
    image: fjolsvin/python-base
    build:
      context: ./base
      dockerfile: alpine.Dockerfile
      args:
        - PYTHON_VERSION=3.9.2
  operator:
    build:
      context: ./dev
      dockerfile: alpine.Dockerfile
      args:
        - USER=operator
        - UID=1000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ../:/workspace:cached
    depends_on:
      - base
    command:
      - /bin/sh
      - -cex
      - while sleep 1000; do :; done