version: "3"
services:
  consul-replicate:
    image: fjolsvin/consul-replicate
    build:
      context: ./
      dockerfile: consul-replicate.Dockerfile
      args:
        - USER=operator
  consul-replicate:
    image: fjolsvin/consul-replicate
    build:
      context: ./
      dockerfile: consul-replicate.Dockerfile
      args:
        - USER=operator
