version: "3"
services:
  consul-replicate:
    image: fjolsvin/consul-replicate
    build:
      context: ./
      dockerfile: consul-replicate.Dockerfile
      args:
        - USER=operator
  minikube:
    image: fjolsvin/minikube
    build:
      context: ./
      dockerfile: minikube.Dockerfile
      args:
        - USER=operator
    # cap_add:
    #   - SYS_PTRACE
    # security_opt:
    #   - seccomp:unconfined

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      # - 2375
      - 8443
    command: /bin/sh -c "while sleep 1000; do :; done"

