version: "3"
services:
  golang-base-alpine:
    # ─────────────────────────────────────────────────────────────────
    # docker-compose -f build.docker-compose.yml build golang-base-alpine
    # ─────────────────────────────────────────────────────────────────
    image: fjolsvin/golang-base-alpine
    build:
      context: ./base
      dockerfile: alpine.Dockerfile
      args:
        - GURU_VERSION=master
        - GOPLS_VERSION=latest
        - DELVE_VERSION=latest
        - GOTESTS_VERSION=latest
        - GOMODIFYTAGS_VERSION=latest
        - GOPLAY_VERSION=latest
        - GOLANGCI_LINT_VERSION=latest
      
  vscode-golang-alpine:
    # ─────────────────────────────────────────────────────────────────
    # docker-compose -f build.docker-compose.yml build vscode-golang-alpine
    # ─────────────────────────────────────────────────────────────────
    image: fjolsvin/vscode-golang-alpine
    build:
      context: ./vscode
      dockerfile: alpine.Dockerfile
      args:
        - USER=code
        - UID=1000
    depends_on:
      - golang-base-alpine
