name: "python"
on:
  push:
    paths:
    - 'python/**.Dockerfile'
    - 'python/build.docker-compose.yml'
  workflow_dispatch:

jobs:
  build-and-push:
    defaults:
      run:
        working-directory: ./python
    name: "build and push docker image(s)"
    runs-on: ubuntu-18.04
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: "Login to Docker Container Repository"
        run: echo ${DOCKER_PASSWORD} | docker login -u ${DOCKER_USERNAME} --password-stdin
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - name: "prune docker"
        shell: bash
        run: >
          set -ex &&
          docker system prune 
          --all 
          --volumes 
          --force
      - name: "build and tag the image"
        shell: bash
        run: >
          set -ex &&
          docker-compose
          -f build.docker-compose.yml
          build
      - name: "push fjolsvin/python-base-alpine:latest"
        shell: bash
        run: >
          set -ex &&
          docker push fjolsvin/python-base-alpine:latest
      - name: "push fjolsvin/vscode-python-alpine:latest"
        shell: bash
        run: >
          set -ex &&
          docker push fjolsvin/vscode-python-alpine:latest
