name: "python"
on:
  push:
    paths:
    - 'python/base/alpine.Dockerfile'
    - 'python/vscode/alpine.Dockerfile'
    - 'python/build.docker-compose.yml'
  workflow_dispatch:
jobs:
# ────────────────────────────────────────────────────────────────────────────────
  python-base-alpine:
    defaults:
      run:
        working-directory: ./python
    name: "build and push docker image(s)"
    runs-on: ubuntu-18.04
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: "build and tag the python-base-alpine image"
        shell: bash
        run: >
          set -ex &&
          docker-compose
          -f build.docker-compose.yml
          build python-base-alpine
      - name: "Login to Docker Container Repository"
        run: echo ${DOCKER_PASSWORD} | docker login -u ${DOCKER_USERNAME} --password-stdin
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - name: "push fjolsvin/python-base-alpine:latest"
        shell: bash
        run: >
          set -ex &&
          docker push fjolsvin/python-base-alpine:latest
# ────────────────────────────────────────────────────────────────────────────────
  vscode-python-alpine:
    name: "build and push docker image(s)"
    runs-on: ubuntu-18.04
    needs: python-base-alpine
    defaults:
      run:
        working-directory: ./python
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: "build and tag the vscode-python-alpine image"
        shell: bash
        run: >
          set -ex &&
          docker-compose
          -f build.docker-compose.yml
          build vscode-python-alpine
      - name: "Login to Docker Container Repository"
        run: echo ${DOCKER_PASSWORD} | docker login -u ${DOCKER_USERNAME} --password-stdin
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - name: "push fjolsvin/vscode-python-alpine:latest"
        shell: bash
        run: >
          set -ex &&
          docker push fjolsvin/vscode-python-alpine:latest