name: "tools"
on:
  schedule:
    - cron: "0 0 * * *"
  push:
    paths:
      - "tools/**/Dockerfile"
      - ".github/workflows/tools.yml"
      - "builder/rust/alpine/*"
  workflow_dispatch:
jobs:
  upx:
    defaults:
      run:
        working-directory: ./tools/upx
    name: "build and push upx docker image"
    runs-on: ubuntu-18.04
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true
      - name: "Login to Docker Container Repository"
        run: echo ${DOCKER_PASSWORD} | docker login -u ${DOCKER_USERNAME} --password-stdin
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - name: "build docker image"
        shell: bash
        run: >
          set -ex &&
          bash build.sh
  changes:
    runs-on: ubuntu-latest
    outputs:
      clog: ${{ steps.filter.outputs.clog }}
      convco: ${{ steps.filter.outputs.convco }}
      jen: ${{ steps.filter.outputs.jen }}
      petname: ${{ steps.filter.outputs.petname }}
      tojson: ${{ steps.filter.outputs.tojson }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            clog:
              - 'tools/clog/**'
            convco:
              - 'tools/convco/**'
            jen:
              - 'tools/jen/**'
            petname:
              - 'tools/petname/**'
            tojson:
              - 'tools/tojson/**'
  convco:
    needs: [upx, changes]
    if: ${{ github.event_name == 'schedule' && needs.changes.outputs.convco == 'true' }}
    defaults:
      run:
        working-directory: ./tools/convco
    name: "build and push convco docker image"
    runs-on: ubuntu-18.04
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true
      - name: "Login to Docker Container Repository"
        run: echo ${DOCKER_PASSWORD} | docker login -u ${DOCKER_USERNAME} --password-stdin
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - name: "build docker image"
        shell: bash
        run: >
          set -ex &&
          bash build.sh
  clog:
    if: ${{ github.event_name == 'schedule' || needs.changes.outputs.clog == 'true' }}
    needs: [upx, changes]
    defaults:
      run:
        working-directory: ./tools/clog
    name: "build and push clog docker image"
    runs-on: ubuntu-18.04
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true
      - name: "Login to Docker Container Repository"
        run: echo ${DOCKER_PASSWORD} | docker login -u ${DOCKER_USERNAME} --password-stdin
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - name: "build docker image"
        shell: bash
        run: >
          set -ex &&
          bash build.sh
  jen:
    if: ${{ github.event_name == 'schedule' || needs.changes.outputs.jen == 'true' }}
    needs: [upx, changes]
    defaults:
      run:
        working-directory: ./tools/jen
    name: "build and push jen docker image"
    runs-on: ubuntu-18.04
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true
      - name: "Login to Docker Container Repository"
        run: echo ${DOCKER_PASSWORD} | docker login -u ${DOCKER_USERNAME} --password-stdin
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - name: "build docker image"
        shell: bash
        run: >
          set -ex &&
          bash build.sh
  petname:
    needs: [upx, changes]
    if: ${{ github.event_name == 'schedule' || needs.changes.outputs.petname == 'true' }}
    defaults:
      run:
        working-directory: ./tools/petname
    name: "build and push petname docker image"
    runs-on: ubuntu-18.04
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true
      - name: "Login to Docker Container Repository"
        run: echo ${DOCKER_PASSWORD} | docker login -u ${DOCKER_USERNAME} --password-stdin
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - name: "build docker image"
        shell: bash
        run: >
          set -ex &&
          bash build.sh
  tojson:
    needs: [upx, changes]
    if: ${{ github.event_name == 'schedule' || needs.changes.outputs.tojson == 'true' }}
    defaults:
      run:
        working-directory: ./tools/tojson
    name: "build and push tojson docker image"
    runs-on: ubuntu-18.04
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true
      - name: "Login to Docker Container Repository"
        run: echo ${DOCKER_PASSWORD} | docker login -u ${DOCKER_USERNAME} --password-stdin
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - name: "build docker image"
        shell: bash
        run: >
          set -ex &&
          bash build.sh
